---
# tasks file for puppet
- yum: name={{ item }} state=present
  tags: puppet
  with_items:
  - https://yum.puppetlabs.com/puppetlabs-release-el-{{ ansible_distribution_major_version }}.noarch.rpm

- yum: name=puppet state=present
  tags: puppet

